Feature/limitcheck
eclipse/kuksa.val pull request #148
Opened 2021-03-30 19:44 UTC by SebastianSchildt

Fixes #46 and rewrites the type check code

2021-03-31 12:27 UTC, wenwenchenbosch requested changes

2021-03-31 12:27 UTC, wenwenchenbosch commented on src/VSSTypeSanitizer.cpp
> +    if (dt == "uint8") {
so many ifs... but it is ok :)

2021-03-31 12:27 UTC, wenwenchenbosch commented on src/VSSTypeSanitizer.cpp
> +    double dval = val.as<long double>();
use https://en.cppreference.com/w/cpp/string/basic_string/stol or maybe there is better function for it. I did not search so much. but what you did is unsafe. see the failing testcases :p

2021-04-01 08:22 UTC, wenwenchenbosch commented
now it is broken: https://kuksaval.northeurope.cloudapp.azure.com/blue/organizations/jenkins/kuksaval-upstream/detail/PR-148/2/tests

2021-04-01 10:49 UTC, SebastianSchildt commented on test/unit-test/KuksavalUnitTest.cpp
> +    string test_path_int8 = "Vehicle.Body.Mirrors.Right.Tilt";
test requires unlimited sensors (without min/max)

2021-04-08 12:18 UTC, wenwenchenbosch approved these changes

2021-04-08 12:18 UTC, merged