Add script to print certificate path
eclipse/kuksa.val pull request #153
Opened 2021-04-01 09:47 UTC by wenwenchenbosch

so that it is easier for user to find certificates if just use pip packages

2021-04-13 13:22 UTC, wenwenchenbosch commented on MANIFEST.in
> +recursive-include kuksa_viss_client *
```suggestion
recursive-include kuksa_viss_client *2
```

2021-04-14 09:18 UTC, SebastianSchildt commented
Did we (intentionally) loose the capability to start a development version directly?

```
sebastian@sebastian-VirtualBox:~/kuksa.val/kuksa_viss_client$ python3 __main__.py 
Traceback (most recent call last):
  File "__main__.py", line 25, in <module>
    from kuksa_certificates import __certificate_dir__
ImportError: cannot import name '__certificate_dir__' from 'kuksa_certificates' (/home/sebastian/.local/lib/python3.8/site-packages/kuksa_certificates/__init__.py)
```

2021-04-14 16:29 UTC, wenwenchenbosch commented
@SebastianSchildt the issue should be fixed now

2021-04-15 16:56 UTC, wenwenchenbosch commented
also solve #164

2021-04-16 10:46 UTC, SebastianSchildt requested changes
One question: Didn't we decide, the client should also print the default cert dir when starting?

But I still have another problem. I can now start the client locally (from github), but the new command crashes

```
 python3 __main__.py 
Welcome to kuksa viss client 0.1.7.post126

                  `-:+o/shhhs+:`                  
                ./oo/+o/``.-:ohhs-                
              `/o+-  /o/  `..  :yho`              
              +o/    /o/  oho    ohy`             
             :o+     /o/`+hh.     sh+             
             +o:     /oo+o+`      /hy             
             +o:     /o+/oo-      +hs             
             .oo`    oho `oo-    .hh:             
              :oo.   oho  -+:   -hh/              
               .+o+-`oho     `:shy-               
                 ./o/ohy//+oyhho-                 
                    `-/+oo+/:.             


connect to wss://127.0.0.1:8090
Websocket connected!!
Test Client> info 
Kuksa viss client 0.1.7.post126
Uri: https://github.com/eclipse/kuksa.val
Author: Sebastian Schildt, Naresh Nayak, Wenwen Chen
Copyright: Copyright 2020 Robert Bosch GmbH
EXCEPTION of type 'AttributeError' occurred with message: 'module 'kuksa_certificates' has no attribute '__certificate_dir__''
To enable full traceback, run the following command: 'set debug true'
Test Client> 
```

2021-04-19 12:54 UTC, SebastianSchildt approved these changes
Now I finally can't break it :)

2021-04-19 12:56 UTC, merged