Stresstest changed to use kuksa_viss_client
eclipse/kuksa.val pull request #205
Opened 2021-06-08 06:36 UTC by linussieweke

#197

2021-06-08 10:46 UTC, wenwenchenbosch commented on test/stresstest/config.ini
> +insecure=true
insecure should not be necessary any more. can you test it

2021-06-08 10:51 UTC, wenwenchenbosch commented on test/stresstest/stressClient.py
> +        args = parser.parse_args()
args hier for argument parser does not necessary any more richtig?

2021-06-08 10:54 UTC, wenwenchenbosch commented on test/stresstest/stressClient.py
> +        config = {'ip':self.cfg['ip'],
`config` hier is useless

2021-06-14 07:43 UTC, wenwenchenbosch requested changes

2021-06-14 07:43 UTC, wenwenchenbosch commented on test/stresstest/stressClient.py
> +        """self.cfg['ip'] = vsscfg.get("ip")
```suggestion
        self.cfg['ip'] = vsscfg.get("ip")
```

2021-06-14 10:17 UTC, linussieweke commented on test/stresstest/stressClient.py
> +        """self.cfg['ip'] = vsscfg.get("ip")
Agreed, forgot to commit cleanup...

2021-06-15 08:42 UTC, wenwenchenbosch approved these changes

2021-06-15 08:42 UTC, merged