Record replay develop
eclipse/kuksa.val pull request #219
Opened 2021-07-20 08:09 UTC by linussieweke

Implemented record feature using boost::log. Had to change abortion process of the server to be able to save the log file to the correct location due to library limitations. Also added command line options for easy customisation

2021-07-26 15:02 UTC, wenwenchenbosch commented
@linussieweke pls check why jenkins can not build your branch

2021-07-26 15:19 UTC, wenwenchenbosch requested changes

2021-07-26 15:19 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +    log("get;" + path.to_string() + "");
I do not think it is necessary to log getSignal

2021-07-26 15:19 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +    BOOST_LOG(lg) << msg;
any special reason to wrap this function?

2021-07-26 15:19 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +    logfile_name_ = "record-%Y%m%d_%H%M%S.log.csv";
```suggestion
    logfile_name_ = "record-%Y%m%d.log.csv";
```
to avoid number of log files?

2021-07-26 15:19 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +            keywords::auto_flush = true
maybe necessary to append a previously written files using:
```
            keywords::open_mode = std::ios_base::out | std::ios_base::app,
```

2021-07-26 15:19 UTC, wenwenchenbosch commented on src/main.cpp
> +  delete gDatabase;
really necessary to delete explicitly?

2021-07-27 08:36 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +bool VssDatabase_Record::isActor(const jsoncons::json &element){return overClass_.isActor(element);}
```suggestion
bool VssDatabase_Record::isActor(const jsoncons::json &element){return VssDatabase::isActor(element);}
```

2021-07-27 08:44 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +        workingDir = getexepath();
=> working directory `.`

2021-07-27 08:46 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +        workingDir = getexepath();
using cwd

2021-07-27 08:51 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +    log("set;" + path.to_string() + ";" + json_val);
```suggestion
    BOOST_LOG(lg) << "set;" << path.to_string() << ";" << json_val;
```

2021-07-27 08:54 UTC, wenwenchenbosch commented on src/VssDatabase_Record.cpp
> +    log("get;" + path.to_string() + "");
add option for command line argument for get, set, get-set

2021-07-27 08:58 UTC, wenwenchenbosch commented on src/main.cpp
> +  delete gDatabase;
check exception case

2021-07-27 09:00 UTC, wenwenchenbosch commented on src/main.cpp
> +    ("record", program_options::value<bool>() -> default_value(0),
maybe enum for get or/and set

2021-07-27 09:06 UTC, wenwenchenbosch commented on src/main.cpp
> +    gDatabase = static_cast<VssDatabase*>(database.get());
rm gDatabase

2021-07-27 12:42 UTC, linussieweke commented on include/VssDatabase.hpp
> +  bool isActor(const jsoncons::json &element);
comes from using the overClass, will be resolved by using VssDatabase as Base class

2021-07-27 12:46 UTC, linussieweke commented on include/VssDatabase_Record.hpp
> +  friend class w3cunittest;
werden nachgereicht

2021-07-27 12:48 UTC, linussieweke commented on src/VssDatabase_Record.cpp
> +        workingDir = getexepath();
cwd is not necessar when using `.`

2021-08-10 09:02 UTC, wenwenchenbosch requested changes
pls also update https://github.com/eclipse/kuksa.val/blob/master/doc/usage.md for new option

2021-08-10 09:02 UTC, wenwenchenbosch commented on src/main.cpp
> +    ("record", program_options::value<int>() -> default_value(noRecord),
better use string instead of integer, better usability

2021-08-10 10:03 UTC, wenwenchenbosch requested changes
`enum` is not necessary anymore, if program option does not support `enum` type

2021-08-10 10:03 UTC, wenwenchenbosch commented on src/main.cpp
> +        if(stoi(variables["record"].as<string>()) == noGet)
```suggestion
        if(stoi(variables["record"].as<string>()) == "set only")
```

2021-08-10 10:03 UTC, wenwenchenbosch commented on src/main.cpp
> +        else if(stoi(variables["record"].as<string>()) == withGet)
```suggestion
        else if(stoi(variables["record"].as<string>()) == "set and get")
```

2021-08-10 13:47 UTC, wenwenchenbosch requested changes

2021-08-10 13:47 UTC, wenwenchenbosch commented on src/main.cpp
> +        else if(variables["record"].as<string>() == "recordSetandGet")
Is there any feature built for recordSetandGet? My lock file does not contain any get request after I start with the command: ` ./kuksa-val-server --record recordSetandGet`

2021-08-10 13:47 UTC, wenwenchenbosch commented on src/main.cpp
> +        else if(variables["record"].as<string>() == "recordSetandGet")
another point: if camelcase, pls always camelcase
```suggestion
        else if(variables["record"].as<string>() == "recordSetAndGet")
```

2021-08-24 08:27 UTC, wenwenchenbosch approved these changes

2021-08-24 08:35 UTC, merged