220 improve client performance
eclipse/kuksa.val pull request #221
Opened 2021-08-09 07:47 UTC by wenwenchenbosch

solve #220

2021-08-09 20:43 UTC, SebastianSchildt reviewed
See small comments.

2021-08-09 20:43 UTC, SebastianSchildt commented on kuksa_feeders/dbc2val/dbcfeeder.py
> +
Why changing this?

2021-08-09 20:43 UTC, SebastianSchildt commented on kuksa_viss_client/__init__.py
> +        self.loop.set_debug(True)
Is this needed in production?

2021-08-09 20:58 UTC, SebastianSchildt requested changes
Much faster 👍   🥇 

Should merge, but I still feel we should not run in asyncio debug mode

2021-08-10 07:37 UTC, wenwenchenbosch commented on kuksa_viss_client/__init__.py
> +        self.loop.set_debug(True)
```suggestion
```

2021-08-11 08:20 UTC, SebastianSchildt approved these changes

2021-08-11 08:20 UTC, merged