Add databroker
eclipse/kuksa.val pull request #279
Opened 2022-05-25 11:11 UTC by argerus

Signed-off-by: John Argérus <fixed-term.john.argerus@se.bosch.com>

2022-06-03 18:59 UTC, SebastianSchildt requested changes
Hi @argerus  , can you also modify the main project Readme table with a small row referencing data broker? 

For example, something like this

| License | Component      | Description |
|--|--|--|
| [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0) | [kuksa-databroker](kuksa_databroker) | Efficient in-vehicle signal broker written in RUST    |

We probably need to get more wordy there in the near future, but for now let's at least have a complete TOC 😄

2022-06-03 20:20 UTC, argerus commented
> Hi @argerus , can you also modify the main project Readme table

done

2022-06-07 06:58 UTC, SebastianSchildt reviewed
Looking good, just two minor comments/questions ^^

2022-06-07 08:22 UTC, argerus commented on kuksa_databroker/README.md
> +./vss-tools/vspec2json.py -I spec -i :uuid.txt spec/VehicleSignalSpecification.vspec vss.json
> Outdated?

Yes, fixed.

2022-06-07 10:43 UTC, SebastianSchildt approved these changes
lgtm

2022-06-07 10:43 UTC, merged