kuksa_client: Allow getting/setting/subscribing of multiple target values from CLI
eclipse/kuksa.val pull request #418
Opened 2022-11-28 13:35 UTC by romainletendart

2022-11-29 11:34 UTC, SebastianSchildt requested changes
I can not connect with this branch, but not sure, maybe it just needs a rebase? I observe this

```
Default tokens directory: /Users/scs2rng/.local/share/virtualenvs/testkc-fNFfcNs5/lib/python3.10/site-packages/kuksa_certificates/jwt

connect to wss://127.0.0.1:8090
Disconnected!! [Errno 61] Connect call failed ('127.0.0.1', 8090)
Error: Websocket could not be connected or the gRPC channel could not be created.
Server disconnected.
Test Client> setServerAddress 127.0.0.1  55556 -p grpc
Setting Server Address to 127.0.0.1:55556 with protocol grpc
Test Client> connect -i
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/scs2rng/.local/share/virtualenvs/testkc-fNFfcNs5/lib/python3.10/site-packages/kuksa_client/__init__.py", line 105, in run
    self.loop.run_until_complete(self.backend.mainLoop())
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/scs2rng/.local/share/virtualenvs/testkc-fNFfcNs5/lib/python3.10/site-packages/kuksa_client/cli_backend/grpc.py", line 208, in mainLoop
    async with kuksa_client.grpc.VSSClient(self.serverIP, self.serverPort) as vss_client:
AttributeError: __aenter__
Error: Websocket could not be connected or the gRPC channel could not be created.
gRPC channel disconnected.
Test Client> 
```

2022-11-29 13:10 UTC, SebastianSchildt commented
Subscribing multiple entries works, even for values. Is there a reason multiple is only supported for targetValues?

2022-11-29 13:56 UTC, romainletendart commented
> Subscribing multiple entries works, even for values. Is there a reason multiple is only supported for targetValues?

With the small amount of time I had, I only did what was necessary for the PoC.

2022-11-30 10:57 UTC, SebastianSchildt approved these changes
Works, and is an improvement, so let's merge this now. Added an issue to potentially extend this for setting (non-target) values as well in the future

2022-11-30 10:57 UTC, merged