Making jemalloc an optional feature
eclipse/kuksa.val pull request #468
Opened 2023-01-25 13:51 UTC by SebastianSchildt

Should solve #460

2023-01-25 17:25 UTC, argerus requested changes
Looks good, .
But can I suggest that we call the feature `jemalloc` instead.

2023-01-25 17:37 UTC, argerus requested changes

2023-01-25 17:37 UTC, argerus commented on kuksa_databroker/databroker/Cargo.toml
```suggestion
[features]
jemalloc = ["dep:jemallocator"]

```

2023-01-26 12:51 UTC, SebastianSchildt commented
Fixed.
Probably not directly related, but my cargo was thinking serde_derive was missing from Cargo.lock, so I also added it, so at least version is pinned.

2023-01-27 11:04 UTC, argerus approved these changes

2023-01-27 16:14 UTC, merged