Describe Docker Desktop workarounds for Windows and Mac OS
eclipse/kuksa.val pull request #494
Opened 2023-03-01 16:26 UTC by SebastianSchildt

Add hints how to use Docker Desktop.

This came up in #489 , so let's preserve the knowledge

2023-03-01 18:24 UTC, lukasmittag requested changes

2023-03-01 18:24 UTC, lukasmittag commented on doc/quickstart.md
> +Most likely, to get productive with KUKSA.val you want to interact with it programmatically. Here is you you do it with our Python library.
```suggestion
Most likely you want to get productive with KUKSA.val in a developing way. The approach would then be to use our Python library.
```

2023-03-02 08:35 UTC, SebastianSchildt commented on doc/quickstart.md
> +Most likely, to get productive with KUKSA.val you want to interact with it programmatically. Here is you you do it with our Python library.
I tried rewording this

2023-03-02 08:37 UTC, lukasmittag approved these changes

2023-03-02 11:40 UTC, merged