Feature/go client array support
eclipse/kuksa.val pull request #570
Opened 2023-05-26 15:12 UTC by lukasmittag

2023-06-01 09:03 UTC, SebastianSchildt requested changes
It seems the paths in some println outputs are incorrect

2023-06-01 09:03 UTC, SebastianSchildt commented on kuksa_go_client/main.go
> +				log.Println("Vehicle.ADAS.ABS.IsEnabled: " + value.(string))
Should also be DTCList in print?

2023-06-01 09:03 UTC, SebastianSchildt commented on kuksa_go_client/main.go
> +				log.Println("Vehicle.ADAS.ABS.IsEnabled: " + value.(string))
DTCList in print

2023-06-01 09:03 UTC, SebastianSchildt commented on kuksa_go_client/main.go
> +			log.Println("Vehicle.ADAS.ABS.IsEnabled: " + val.(string))
Needs to be Speed in println

2023-06-16 14:36 UTC, erikbosch commented
Could you do a quick check if your comments have been addressed @SebastianSchildt ?

2023-06-19 13:03 UTC, merged