Nodred
eclipse/kuksa.val pull request #58
Opened 2020-10-13 17:12 UTC by wenwenchenbosch

2020-10-14 15:32 UTC, SebastianSchildt requested changes
Tested, and all works. Just adapt the Readme (dependency and TODO note) and this is fine.

Not a problem, but I noticed, the websocket examples uses Vehicle.OBD.Speed and MQTT uses Vehicle.Speed

2020-10-14 15:32 UTC, SebastianSchildt commented on examples/node-red/README.md
>  ## MQTT
Also needs something called node-red-contrib-web-worldmap , maybe mention it

2020-10-14 15:32 UTC, SebastianSchildt commented on examples/node-red/README.md
>  It is also possible to use node-red as websocket client, it is also configured in the json file, but it does not work jet
This is possible now

2020-10-15 07:46 UTC, wenwenchenbosch commented
> Tested, and all works. Just adapt the Readme (dependency and TODO note) and this is fine.
> 
> Not a problem, but I noticed, the websocket examples uses Vehicle.OBD.Speed and MQTT uses Vehicle.Speed

Hi @SebastianSchildt: good reviewed :+1:  But which one should I use?

2020-10-15 12:01 UTC, wenwenchenbosch commented
> > Tested, and all works. Just adapt the Readme (dependency and TODO note) and this is fine.
> > Not a problem, but I noticed, the websocket examples uses Vehicle.OBD.Speed and MQTT uses Vehicle.Speed
> 
Hi @SebastianSchildt: all review findings fixed

2020-10-15 12:40 UTC, SebastianSchildt approved these changes
Only changes Readme, and extends/replaces the nodered flows already in master

Can be merged 👯‍♀️    @daschubert @eriksven

2020-10-19 11:43 UTC, merged